### ISSUE TITLE
permission issues

### ISSUE THREAD

**Issue by pixeline** [telusdigital/ansible-upstart#15]
This task

```yml
- name: ATTENDANCES _ configure upstart
  include_role:
    name: telusdigital.upstart
  become: yes 
  become_user: root
  vars:
    upstart_name: bcd_attendances
    upstart_runtime_root: "{{ deploy_helper.current_path }}"
    upstart_description: "Upstart for Attendances App"
    upstart_user: "{{ web_user }}"
    upstart_environment_global: no
    upstart_respawn: yes
    upstart_start_on:
        - filesystem
    upstart_stop_on:
        - shutdown
    upstart_exec_path: 'sudo node {{ deploy_helper.current_path }}/web/attendances/app.js --prod'
    upstart_respawn: yes
````
triggers this error :

```` 
TASK [telusdigital.logrotate : Upload Config | upstart] ******************************************************************************************
skipping: [inside.example.org]

TASK [telusdigital.upstart : Upload Upstart Script config | bcd_attendances] *********************************************************************
System info:
  Ansible 2.4.2.0; Darwin
  Trellis at "Update `vagrant_box_version` to `>= 201801.02.0`"
---------------------------------------------------
Failed to get information on remote file (/etc/init/bcd_attendances.conf):
sudo: a password is required

````
I'm wondering if i'm using the role correctly. Does upstart require the root user ?
