### ISSUE TITLE
Missing service file : Unit *.service not found

### ISSUE THREAD

**Issue by pixeline** [telusdigital/ansible-upstart#16]
I've successfully deployed an upstart using this : 

```yml

- name: Setup upstart
  hosts: web:&{{ env }}
  remote_user: "{{ admin_user }}"
  roles:
    - telusdigital.upstart
  become: yes 
  vars:
    upstart_name: bcd_attendances
    upstart_description: "Upstart for Attendances App"
    upstart_environment_global: no
    upstart_respawn: yes
    upstart_start_on:
        - filesystem
    upstart_stop_on:
        - shutdown
    upstart_exec_path: 'sudo -u root node {{ deploy_helper.current_path }}/web/attendances/app.js --prod'
```

But when I try to run the service
`service bcd_attendances start`
it returns
````
Failed to start bcd_attendances.service: Unit bcd_attendances.service not found.
````

What am I doing wrong ?
